language: scala
jdk:
  - openjdk6
scala:
# https://github.com/ensime/ensime-server/issues/866
#  - 2.9.2
#  - 2.9.3
#  - 2.10.4
  - 2.11.6
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
addons:
  apt_packages:
  # https://github.com/travis-ci/apt-package-whitelist
  - curl
  - openjdk-6-source
  #- openjdk-7-source
  # Travis doen't allow ppa's on its docker infrastructure but by
  # installing emacs23-gtk we get most of the dependencies we need to
  # run our own build of emacs-24.4.
  - emacs23-gtk
install:
  - curl -L $EMACS_URL | tar xjf - -C $HOME &&
    export EMACS=$HOME/emacs-${EMACS_VERSION}-bin/bin/emacs-${EMACS_VERSION} &&
    $EMACS --version
script:
  - test/run_emacs_tests.sh #2>&1 | tee stdout | grep "Starting test"
after_success:
  - if [ ! -z "$UNDERCOVER" ] ; then curl -v -include --form json_file=@coveralls.json https://coveralls.io/api/v1/jobs ; fi
#after_failure:
#  - cat stdout
env:
  global:
    - ENSIME_TEST_SERVER_VERSION=$TRAVIS_SCALA_VERSION
  matrix:
    - EMACS_VERSION=24.1 EMACS_URL=https://www.dropbox.com/s/lf2c9op9wax86y8/emacs-24.1-bin.tar.bz2
    - EMACS_VERSION=24.2 EMACS_URL=https://www.dropbox.com/s/u1isy5ywhu5a2yg/emacs-24.2-bin.tar.bz2
    - EMACS_VERSION=24.3 EMACS_URL=https://www.dropbox.com/s/iy3dqx5r378rpe6/emacs-24.3-bin.tar.bz2 UNDERCOVER=true
# emacs 24.4 being weird https://github.com/ensime/ensime-server/issues/862
#    - EMACS_VERSION=24.4 EMACS_URL=https://www.dropbox.com/s/y3bhjrchxrm9reh/emacs-24.4-bin.tar.bz2
